language: minimal
git:
  depth: false
  quiet: true
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
matrix:
  include:
  - name: Arduino tests (on Linux default)
    cache:
      directories:
        - ~/arduino_ide
        - ~/.arduino15/packages/
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "LiquidCrystal_PCF8574"
    script: cd water_system && build_main_platforms && ls -la
  - name: Unit tests g++ / focal / directly proportional sensors
    dist: focal
    language: cpp
    compiler: g++
    script: sed -i  's@//\s*#define\s*SENSOR_USES_DIRECT_PROPORTION@#define SENSOR_USES_DIRECT_PROPORTION@' water_system/ws_defs.h && cd water_system/test && make
  - name: Unit tests g++ / focal / inverse proportional sensors
    dist: focal
    language: cpp
    compiler: g++
    script: sed -i  's@\(.*\)#define\s*SENSOR_USES_DIRECT_PROPORTION@// disabled SENSOR_USES_DIRECT_PROPORTION@' water_system/ws_defs.h && cd water_system/test && make
  - name: Unit tests g++ / focal
    dist: focal
    language: cpp
    compiler: g++
    script: cd water_system/test && make
  - name: Unit tests clang++ / focal
    dist: focal
    language: cpp
    compiler: clang++
    script: cd water_system/test && make
  - name: Unit tests g++ / bionic
    dist: bionic
    language: cpp
    compiler: g++
    script: cd water_system/test && make
  - name: Unit tests clang++ / bionic
    dist: bionic
    language: cpp
    compiler: clang++
    script: cd water_system/test && make
  - name: Unit tests clang++ / xenial
    dist: xenial
    language: cpp
    compiler: clang++
    script: cd water_system/test && make
#notifications:
#  email:
#    on_success: change
#    on_failure: change
