language: minimal
sudo: false
git:
  depth: false
  quiet: true
matrix:
  include:
  - name: Arduino tests
    cache:
      directories:
        - ~/arduino_ide
        - ~/.arduino15/packages/
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "LiquidCrystal_PCF8574"
    script: cd water_system && build_main_platforms
  - name: Unit tests g++
    language: cpp
    compiler: g++
    script: cd water_system/test && make
  - name: Unit tests clang++
    language: cpp
    compiler: clang++
    script: cd water_system/test && make
  - name: Unit tests clang++ / xenial
    dist: xenial
    language: cpp
    compiler: clang++
    script: cd water_system/test && make
#notifications:
#  email:
#    on_success: change
#    on_failure: change
