language: cpp
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit SleepyDog Library","Adafruit FONA Library"
script:
  - cd water_system
  - build_main_platforms
#notifications:
#  email:
#    on_success: change
#    on_failure: change
