language: minimal
git:
  depth: false
  quiet: true
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
matrix:
  include:
  - name: Arduino tests (on Linux default)
    cache:
      directories:
        - ~/arduino_ide
        - ~/.arduino15/packages/
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "LiquidCrystal_PCF8574,EEPROMWearLevel"
    script: cd water_system && build_main_platforms && ls -la
  - name: Unit tests g++ / focal / direct and inverse proportional sensors
    dist: focal
    language: cpp
    compiler: g++
    script: cd water_system/test && ./direct_inverse_test.sh
  - name: Unit tests clang++ / focal / direct and inverse proportional sensors
    dist: focal
    language: cpp
    compiler: clang++
    script: cd water_system/test && ./direct_inverse_test.sh
  - name: Unit tests g++ / bionic / direct and inverse proportional sensors
    dist: bionic
    language: cpp
    compiler: g++
    script: cd water_system/test && ./direct_inverse_test.sh
  - name: Unit tests clang++ / bionic / direct and inverse proportional sensors
    dist: bionic
    language: cpp
    compiler: clang++
    script: cd water_system/test && ./direct_inverse_test.sh
  # - name: Unit tests clang++ / xenial
  #   dist: xenial
  #   language: cpp
  #   compiler: clang++
  #   script: cd water_system/test && make
#notifications:
#  email:
#    on_success: change
#    on_failure: change
